### ISSUE TITLE
Error handeling

### ISSUE THREAD

**Issue by ynk** [ynk/league-championFetcher#9]

**Comment by shepherd-06** [comment]
This cute little project can help you with Error Logging. 
https://github.com/ibtehaz-shawon/zathura

What else do you need?

**Comment by ynk** [comment]
Error handling like, bad gateway. I don't remember how you do these but I should be able to cause them.

**Comment by shepherd-06** [comment]
You have to figure it out how and when the bad gateway is occurring. Otherwise, I will have no idea how to fx them @YannickDC

**Comment by ynk** [comment]
Gotcha, breaking my own server? Consider it done!

**Comment by ynk** [comment]
Not needed anymore
